from enum import Enum

class Constants(Enum):
    COPY_SINGLE_FILE = "COPY_SINGLE_FILE"
    COPY_ALL_FILES = "COPY_ALL_FILES"
    CREATE_FOLDER  = "CREATE_FOLDER"
    CREATE_CONTENT = "CREATE_CONTENT"

